### ISSUE TITLE
deck2pdf: command not found

### ISSUE THREAD

**Issue by de-signal** [melix/deck2pdf#13]
After cloning the github repo, making `./gradlew distZip`, then unzipping the `deck2pdf-0.2-SNAPSHOT.zip`file, I have `deck2pdf: command not found` when I try to generate a pdf. 

what am I doing wrong? 

thanks

**Comment by alexsalas** [comment]
Unzipping the deck2pdf-0.2-SNAPSHOT.zip
The binary is the folder: deck2pdf-0.2-SNAPSHOT\deck2pdf-0.2-SNAPSHOT\bin
Try run in the same folder, because use libraries with relative path.
