### ISSUE TITLE
Error in importing javafx

### ISSUE THREAD

**Issue by albertored** [melix/deck2pdf#14]
I can't build the program. I get an error like

    error: package javafx.scene.web does not exist
    import javafx.scene.web.WebEngine;

for every javafx importing.

I have `java version "1.7.0_65"` installed and a manual installation (`.deb` file from oracle site) of `JavaFX 2.0`. I think the problem is the classpath of `jfxrt.jar`. If I try to compile a simple file with some `JavaFX` importation it works only if I specify the classpath from command line but I don't know how to tell `gradlew` to use that classpath.

**Comment by mojavelinux** [comment]
Another solution is to simply use the Oracle JVM, which includes JavaFX. OpenJDK _still_ doesn't ship with JavaFX.

**Comment by melix** [comment]
Fixing as decent workarounds exist.

**Comment by mojavelinux** [comment]
:+1:
