### ISSUE TITLE
Add option to export slide images to disk

### ISSUE THREAD

**Issue by mojavelinux** [melix/deck2pdf#23]
Add an option that exports each slide as an image as it is creating the PDF.

The benefit of exporting each slide to an image is that those images can then be used independently to create other documents, such as a handout that includes slide notes under each slide image.

**Comment by mojavelinux** [comment]
The implementation seems to be as simple as:

```
javax.imageio.ImageIO.write(bufferedImage, "png", new File("/tmp/slide-" + current + ".png"));
```

...obviously with a path that is based on the export file, though.

The other part is adding an option to the commandline and passing it through.

**Comment by melix** [comment]
Sounds like a useful feature. Maybe we should make the format configurable.

**Comment by mojavelinux** [comment]
> Sounds like a useful feature

I'll do you one better. I'm creating an plugin that combines deck2pdf and Asciidoctor PDF to create slide handouts (for things like training decks). This feature is how I get the images to put into the PDF.

> Maybe we should make the format configurable.

:+1:

I think just PNG and JPG is sufficient to start. Actually, JPG would speed up the plugin I mentioned since decompressing PNG to embed into PDF is quite slow.

We probably need a quality setting as well.

**Comment by mojavelinux** [comment]
I'd be happy if we did this in two steps. First, just enable the export to PNG at normal compression. Then, we can come behind and add the configurations.

**Comment by melix** [comment]
Works for me!
