### ISSUE TITLE
Delegate writing of slide to a dedicated object

### ISSUE THREAD

**Issue by mojavelinux** [melix/deck2pdf#26]
To make the code in Browser less cluttered and more organized, the writing of a slide should be delegated to a dedicated object. The object (of proposed type `SlideWriter`) should be created from a factory (or proposed type `SlideWriterFactory`) in the Browser#doExport method. That object should then receive each slide image object as the slide deck is advanced in the PauseTransition#setOnFinished handler.

We can probably get some milage out of using an abstract base class for the two image writers (png and jpg).

**Comment by melix** [comment]
Fixed through 33e71b7a7aec4eb0a4e4629f882d5e38d880cb9f

**Comment by mojavelinux** [comment]
Amazing. It's like I dreamed about it and it came true...but even better. Great job, @melix!

**Comment by mojavelinux** [comment]
This opens the door (and makes room) for an SVG image writer, which is like the Holy Grail of exporting a deck. One day :)
