### ISSUE TITLE
Release 0.2.1 to jcenter (Bintray)

### ISSUE THREAD

**Issue by mojavelinux** [melix/deck2pdf#27]
It would be extremely helpful for tool integrations if deck2pdf could be released to jcenter (and Maven Central as well).

Currently, we're requiring folks to clone, build and install the project locally, which makes the tool less accessible for developers and a showstopper for non-developers.

**Comment by mojavelinux** [comment]
I think the group should be `me.champeau` (or `me.champeau.deck2pdf`) to be consistent with the Java package name (and main class). Currently, the group is `com.github.melix`.

**Comment by melix** [comment]
I bumped the version to 0.3.0-SNAPSHOT.

**Comment by mojavelinux** [comment]
\o/

**Comment by melix** [comment]
Resolving as 0.3.0 is available in Bintray/JCenter.

**Comment by mojavelinux** [comment]
Thank you!!
